<?xml version="1.0" encoding="utf-8"?>
<Database Name="Volonteers" Class="VolonteersDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=АЛЕКСАНДР-ПК\SQLEXPRESS;Initial Catalog=Volonteers;Integrated Security=True" SettingsObjectName="Models.Properties.Settings" SettingsPropertyName="VolonteersConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Vacancy" Member="Vacancies">
    <Type Name="Vacancy">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="NeededNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsApprovalRequired" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ProjectId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Vacancy_PersonVacancy" Member="PersonVacancies" ThisKey="Id" OtherKey="VacancyId" Type="PersonVacancy" />
      <Association Name="Project_Vacancy" Member="Project" ThisKey="ProjectId" OtherKey="Id" Type="Project" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Opinions" Member="Opinions">
    <Type Name="Opinion">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ObjectPersonId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AuthorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Person_Opinion" Member="Person" ThisKey="AuthorId" OtherKey="Id" Type="Person" IsForeignKey="true" />
      <Association Name="Person_Opinion1" Member="Person1" ThisKey="ObjectPersonId" OtherKey="Id" Type="Person" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Topics" Member="Topics">
    <Type Name="Topic">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ObjectId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Text" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="AuthorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Topic_Comment" Member="Comments" ThisKey="Id" OtherKey="TopicId" Type="Comment" />
      <Association Name="Person_Topic" Member="Person" ThisKey="AuthorId" OtherKey="Id" Type="Person" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Message" Member="Messages">
    <Type Name="Message">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AuthorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RecipientId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="IsNew" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Person_Message" Member="Person" ThisKey="AuthorId" OtherKey="Id" Type="Person" IsForeignKey="true" />
      <Association Name="Person_Message1" Member="Person1" ThisKey="RecipientId" OtherKey="Id" Type="Person" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Comments" Member="Comments">
    <Type Name="Comment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TopicId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="AuthorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Topic_Comment" Member="Topic" ThisKey="TopicId" OtherKey="Id" Type="Topic" IsForeignKey="true" />
      <Association Name="Person_Comment" Member="Person" ThisKey="AuthorId" OtherKey="Id" Type="Person" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Persons" Member="Persons">
    <Type Name="Person">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NickName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ICQNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber1" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PhoneNumber2" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Hobbies" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Skills" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="Person_Opinion" Member="Opinions" ThisKey="Id" OtherKey="AuthorId" Type="Opinion" />
      <Association Name="Person_Opinion1" Member="Opinions1" ThisKey="Id" OtherKey="ObjectPersonId" Type="Opinion" />
      <Association Name="Person_Topic" Member="Topics" ThisKey="Id" OtherKey="AuthorId" Type="Topic" />
      <Association Name="Person_Message" Member="Messages" ThisKey="Id" OtherKey="AuthorId" Type="Message" />
      <Association Name="Person_Message1" Member="Messages1" ThisKey="Id" OtherKey="RecipientId" Type="Message" />
      <Association Name="Person_Comment" Member="Comments" ThisKey="Id" OtherKey="AuthorId" Type="Comment" />
      <Association Name="Person_PersonVacancy" Member="PersonVacancies" ThisKey="Id" OtherKey="PersonId" Type="PersonVacancy" />
    </Type>
  </Table>
  <Table Name="dbo.Projects" Member="Projects">
    <Type Name="Project">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Motto" Type="System.String" DbType="VarChar(140)" CanBeNull="true" />
      <Column Name="OwnerPersonId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Project_Vacancy" Member="Vacancies" ThisKey="Id" OtherKey="ProjectId" Type="Vacancy" />
    </Type>
  </Table>
  <Table Name="dbo.PersonVacancy" Member="PersonVacancies">
    <Type Name="PersonVacancy">
      <Column Name="PersonId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VacancyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Person_PersonVacancy" Member="Person" ThisKey="PersonId" OtherKey="Id" Type="Person" IsForeignKey="true" />
      <Association Name="Vacancy_PersonVacancy" Member="Vacancy" ThisKey="VacancyId" OtherKey="Id" Type="Vacancy" IsForeignKey="true" />
    </Type>
  </Table>
</Database>